config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  resources :agencies
  resources :agents do
    member do
      put :update_seller_favorite
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/agency.rb
class Agency < ApplicationRecord
  has_many :agents, foreign_key: :agencies_id
end

app/models/agent.rb
class Agent < ApplicationRecord
  belongs_to :agency, foreign_key: :agencies_id, optional: true
  scope :seller_favorite, -> { where(seller_favorite: true) }

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController
  before_action :set_agency, only: %i[ show edit update destroy ]

  # GET /agencies or /agencies.json
  def index
    @agencies = Agency.all
  end

  # GET /agencies/1 or /agencies/1.json
  def show
    @agents = @agency.agents
  end

  # GET /agencies/new
  def new
    @agency = Agency.new
  end

  # GET /agencies/1/edit
  def edit
  end

  # POST /agencies or /agencies.json
  def create
    @agency = Agency.new(agency_params)

    respond_to do |format|
      if @agency.save
        format.html { redirect_to agency_url(@agency), notice: "Agency was successfully created." }
        format.json { render :show, status: :created, location: @agency }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agencies/1 or /agencies/1.json
  def update
    respond_to do |format|
      if @agency.update(agency_params)
        format.html { redirect_to agency_url(@agency), notice: "Agency was successfully updated." }
        format.json { render :show, status: :ok, location: @agency }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agencies/1 or /agencies/1.json
  def destroy
    @agency.destroy

    respond_to do |format|
      format.html { redirect_to agencies_url, notice: "Agency was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agency
      @agency = Agency.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def agency_params
      params.require(:agency).permit(:name)
    end
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  before_action :set_agent, only: %i[show edit update destroy update_seller_favorite]

  # GET /agents or /agents.json
  def index
    agents = if params[:search]
               Agent.search(params[:search])
             else
               Agent.all
             end

    @agents = agents.preload(:agency).limit(100)
    @favorite_agents = @agents.seller_favorite.preload(:agency).limit(100)
  end

  # GET /agents/1 or /agents/1.json
  def show; end

  # GET /agents/new
  def new
    @agent = Agent.new
  end

  # GET /agents/1/edit
  def edit; end

  # PATCH/PUT /agents/1 or /agents/1.json with fa
  def update_seller_favorite
    @agent.seller_favorite = params[:seller_favorite]
    @agent.save
  end

  # POST /agents or /agents.json
  def create
    @agent = Agent.new(agent_params)

    respond_to do |format|
      if @agent.save
        format.html { redirect_to agent_url(@agent), notice: 'Agent was successfully created.' }
        format.json { render :show, status: :created, location: @agent }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agents/1 or /agents/1.json
  def update
    respond_to do |format|
      if @agent.update(agent_params)
        format.html { redirect_to agent_url(@agent), notice: 'Agent was successfully updated.' }
        format.json { render :show, status: :ok, location: @agent }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agents/1 or /agents/1.json
  def destroy
    @agent.destroy

    respond_to do |format|
      format.html { redirect_to agents_url, notice: 'Agent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_agent
    @agent = Agent.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def agent_params
    params.require(:agent).permit(:name, :premium, :seller_favorite, :registered, :registered_on, :unregistered_on,
                                  :profile_pageviews, :overall_rating, :review_count, :recommendation_count, :image, :url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index; end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/agencies/_form.html.erb
<%= form_with(model: agency) do |form| %>
  <% if agency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(agency.errors.count, "error") %> prohibited this agency from being saved:</h2>

      <ul>
        <% agency.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/agencies/edit.html.erb
<h1>Editing Agency</h1>

<%= render 'form', agency: @agency %>

<%= link_to 'Show', @agency %> |
<%= link_to 'Back', agencies_path %>

app/views/agencies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Agencies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @agencies && @agencies.each do |agency| %>
      <tr>
        <td><%= link_to agency.name, agency %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%
=begin%>
 
<%= link_to 'New Agency', new_agency_path %> 
<%
=end%>

app/views/agencies/new.html.erb
<h1>New Agency</h1>

<%= render 'form', agency: @agency %>

<%= link_to 'Back', agencies_path %>

app/views/agencies/show.html.erb
<h1><%= @agency.name %></h1>
<% if @agency.agents %>
  <%= render :partial => "shared/agent"%>
<% end %>

app/views/agents/_form.html.erb
<%= form_with(model: agent) do |form| %>
  <% if agent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(agent.errors.count, "error") %> prohibited this agent from being saved:</h2>

      <ul>
        <% agent.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :premium %>
    <%= form.check_box :premium %>
  </div>

  <div class="field">
    <%= form.label :seller_favorite %>
    <%= form.check_box :seller_favorite %>
  </div>

  <div class="field">
    <%= form.label :registered %>
    <%= form.check_box :registered %>
  </div>

  <div class="field">
    <%= form.label :registered_on %>
    <%= form.date_select :registered_on %>
  </div>

  <div class="field">
    <%= form.label :unregistered_on %>
    <%= form.date_select :unregistered_on %>
  </div>

  <div class="field">
    <%= form.label :profile_pageviews %>
    <%= form.number_field :profile_pageviews %>
  </div>

  <div class="field">
    <%= form.label :overall_rating %>
    <%= form.number_field :overall_rating %>
  </div>

  <div class="field">
    <%= form.label :review_count %>
    <%= form.number_field :review_count %>
  </div>

  <div class="field">
    <%= form.label :recommendation_count %>
    <%= form.number_field :recommendation_count %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/agents/edit.html.erb
<h1>Editing Agent</h1>

<%= render 'form', agent: @agent %>
<%
=begin%>
 
<%= link_to 'Show', @agent %> |
<%= link_to 'Back', agents_path %> 
<%
=end%>

app/views/agents/index.html.erb
<p id="notice"><%= notice %></p>


<%= form_tag(agents_path, method: 'get') do %>
  <%= text_field_tag(:search, params[:search]) %>
  <%= submit_tag("Search", name: nil) %>
<% end %>

<h1>Favorite Agents</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Agency</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favorite_agents && @favorite_agents.each do |agent| %>
      <tr>
        <td><%= link_to agent.name, agent %></td>
        <% if agent.agency %>
          <td><%= link_to agent.agency.name, agent.agency %></td>
        <% else %>
          <td></td>
        <% end %>        
        <td><%= button_to "Remove from Favorites", update_seller_favorite_agent_path(agent, seller_favorite: false), :method => :put %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h1>All Agents</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Agency</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agents.each do |agent| %>
      <tr>
        <td><%= link_to agent.name, agent %></td> 
        <% if agent.agency %>
          <td><%= link_to agent.agency.name, agent.agency %></td>
        <% else %>
          <td></td>
        <% end %>
        <% if !agent.seller_favorite %>
          <td><%= button_to "Add to Favorites", update_seller_favorite_agent_path(agent, seller_favorite: true), :method => :put%></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/agents/new.html.erb
<h1>New Agent</h1>

<%
=begin%>
 <%= render 'form', agent: @agent %>

<%= link_to 'Back', agents_path %> 
<%
=end%>

app/views/agents/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @agent.name %></h1>
<p>
  <strong>Name:</strong>
  <%= @agent.name %>
</p>

<p>
  <strong>Premium:</strong>
  <%= @agent.premium %>
</p>

<p>
  <strong>Seller favorite:</strong>
  <%= @agent.seller_favorite %>
</p>

<p>
  <strong>Registered:</strong>
  <%= @agent.registered %>
</p>

<p>
  <strong>Registered on:</strong>
  <%= @agent.registered_on %>
</p>

<p>
  <strong>Unregistered on:</strong>
  <%= @agent.unregistered_on %>
</p>

<p>
  <strong>Profile pageviews:</strong>
  <%= @agent.profile_pageviews %>
</p>

<p>
  <strong>Overall rating:</strong>
  <%= @agent.overall_rating %>
</p>

<p>
  <strong>Review count:</strong>
  <%= @agent.review_count %>
</p>

<p>
  <strong>Recommendation count:</strong>
  <%= @agent.recommendation_count %>
</p>

<p>
  <strong>Image:</strong>
  <%= @agent.image %>
</p>

<p>
  <strong>Url:</strong>
  <%= @agent.url %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hittamaklare</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_agent.html.erb
<h2>Agents</h2>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agents && @agents.each do |agent| %>
      <tr>
        <td><%= link_to agent.name, agent %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/welcome/index.html.erb
<h1>Welcome</h1>
<h2>Agencies</h2>
<%= link_to 'Agencies', agencies_path %> 

<h2>Agents</h2>
<%= link_to 'Agents', agents_path %> 